### ISSUE TITLE
chalk 5.x requires ESM support

### ISSUE THREAD

**Issue by drernie** [TheSwanFactory/ts-cli#5]
Reproducible test case

**Comment by drernie** [comment]
```
const chalk = require("chalk");
              ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ernest/Developer/ts-cli/node_modules/chalk/source/index.js from /Users/ernest/Developer/ts-cli/dist/src/utils.js not supported.
Instead change the require of index.js in /Users/ernest/Developer/ts-cli/dist/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/ernest/Developer/ts-cli/dist/src/utils.js:14:15)
    at Object.<anonymous> (/Users/ernest/Developer/ts-cli/dist/src/index.js:4:17) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v20.5.1
```

**Comment by drernie** [comment]
Trying suggestions from:
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

How can I make my TypeScript project output ESM?

[Read the official ESM guide.](https://www.typescriptlang.org/docs/handbook/esm-node.html)

Quick steps:

1. Make sure you are using TypeScript 4.7 or later.
2. Add "type": "module" to your package.json.
3. Replace "main": "index.js" with "exports": "./index.js" in your package.json.
4. Update the "engines" field in package.json to Node.js 16: "node": ">=16".
5. Add ["module": "node16", "moduleResolution": "node16"](https://www.typescriptlang.org/tsconfig#module) to your tsconfig.json. ([Example](https://github.com/sindresorhus/tsconfig/blob/main/tsconfig.json))
6. Use only full relative file paths for imports: import x from '.'; → import x from './index.js';.
7. Remove namespace usage and use export instead.
8. Use the [node: protocol](https://nodejs.org/api/esm.html#esm_node_imports) for Node.js built-in imports.
9. You must use a .js extension in relative imports even though you're importing .ts files.
10. If you use ts-node, follow https://github.com/TypeStrong/ts-node/issues/1007. [Example config.](https://github.com/sindresorhus/got/blob/5f278d74125608b7abe75941cb6a71e21e0fb892/tsconfig.json#L17-L21)

**Comment by drernie** [comment]
Renaming for ESM support: https://github.com/chalk/chalk/issues/613

https://www.typescriptlang.org/docs/handbook/esm-node.html

however, support for ESM in Node.js is now implemented in Node.js, and the dust has begun to settle.
